### ISSUE TITLE
Knowage Execution Python Function error

### ISSUE THREAD

**Issue by ignaciolazaro** [KnowageLabs/Knowage-Server-Docker#4]
Dear Alessandro

I have a working instance of a docker of knowage (image: knowagelabs/knowage-server-docker:develop) and when I try to execute a simple Function defined with phyton I get the following error at tomcat logs

**EVERE: Servlet.service() for servlet [it.eng.spagobi.rest.application.JAXRSApplication] in context with path **[/knowagedataminingengine] threw exception
org.jboss.resteasy.spi.UnhandledException: java.lang.UnsatisfiedLinkError: Can't load library: /home/spagobi/PythonJpy/jpy/build/lib.linux-x86_64-3.4/jpy.cpython-34m.so****

In folder **/home** does not exist the _**_spagobi_**_ folder, in folder home exists the folder **_knowage_** how to configure python properly?

If I execute a function defined in R I get the following error at internet browser 

**java.lang.NullPointerException
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:745)**

Maybe I need download another different docker image 

Many thanks in advance for your support

BR
Nacho

**Comment by aportosa** [comment]
I guess this is an issue of the docker image. When created, Python and R environments have not been configured properly. We will fix this in the next release.

**Comment by ignaciolazaro** [comment]
Thank you for your reply.
When is planned next release? 
BR

**Comment by aportosa** [comment]
I do not have a release date by now. But hopefully will will provide a minor release on March.

**Comment by ignaciolazaro** [comment]
Dear Alessandro

Do you have any news from the new release with the issue solved?

BR

**Comment by aportosa** [comment]
Dear @ignaciolazaro, 
I'm sorry but I do not have a release date at this very moment...
I can only suggest to use Knowage through standard packages installation

**Comment by aportosa** [comment]
Dear @ignaciolazaro , Knowage 6.2.0 RC has just been released. We will update the docker image shortly.

**Comment by ignaciolazaro** [comment]
Thank you for the new release!!

The tests done are the following

1- I have downloaded new docker
2- I have defined a simple dataset with a CSV file (not sure if it is ok, due no information found at https://download.forge.ow2.org/knowage/Knowage_6.x_CE_Manual.pdf )

3- I have defined a simple R file 

myPredictionFunction (temperature, humidity) { 
  value= 0
  if(temperature>myThresholdTemperature){
    value=1
  }else{
    value=2
  }  
}
4- And in the knowageDataMiningEngine.log file at knowage docker appears these lines of log

Caused by: it.eng.spagobi.utilities.exceptions.SpagoBIRuntimeException: Error starting the Data Mining engine or getting datamining engine execution results!
        at it.eng.spagobi.engines.datamining.common.FunctionExecutor.execute(FunctionExecutor.java:150)
        at it.eng.spagobi.engines.datamining.api.FunctionExecutionResource.executeSampleCatalogFunctionById(FunctionExecutionResource.java:48)
        ... 34 more
Caused by: it.eng.spagobi.utilities.exceptions.SpagoBIRuntimeException: DataMining execution error:No R instance found
        at it.eng.spagobi.engines.datamining.common.FunctionExecutionUtils.buildDataminingResponse(FunctionExecutionUtils.java:298)
        at it.eng.spagobi.engines.datamining.common.FunctionExecutor.execute(FunctionExecutor.java:147)

Well, now what can I do?

R is right installed in docker?

If it is right installed, how to test?

Would you mind to provide a simple R file that can works on this docke version, I suppose you have done some  test before release

Many thanks for your support

Best Regards

**Comment by aportosa** [comment]
The Docker develop tag has been updated with the last Knowage version, but we haven't setup the R/Python environment yet.

**Comment by ignaciolazaro** [comment]
Thanks for the information
Then I will wait before to more tests with Knowage

BR

**Comment by kunthar** [comment]
@ignaciolazaro still waiting? 
@aportosa any progress?

**Comment by ignaciolazaro** [comment]
Yes, yet waiting, 8 months to solve a configuration issue...
