### ISSUE TITLE
http error 500 with 8.1 Docker (on windows and macos)

### ISSUE THREAD

**Issue by agaldemas** [KnowageLabs/Knowage-Server-Docker#51]
I tried today to deploy last version (8.1.0), the docker version on macos, using the docker-compose.yml, 

but when I try to get the login page, the tomcat send back an http 500 Error

We have the same behavior under docker on windows (WSL2)
Whenever the installation seems OK on both !

We tested on Ubuntu, no problem !

in the knowage.log we find some errors : 

```
[http-nio-8080-exec-23] 06 Jul 2021 17:28:52,231 ERROR it.eng.spagobi.commons.filters.ProfileFilter.getUserIdWithSSO:313 - Authentication failed
java.lang.NullPointerException
....
[http-nio-8080-exec-23] 06 Jul 2021 17:28:52,231 ERROR it.eng.spagobi.commons.filters.ProfileFilter.doFilter:177 - Error while service execution
it.eng.spagobi.commons.filters.ProfileFilter$SilentAuthenticationFailedException
        at it.eng.spagobi.commons.filters.ProfileFilter.getUserIdWithSSO(ProfileFilter.java:314)
...
[http-nio-8080-exec-12] 06 Jul 2021 17:28:53,240 ERROR it.eng.spagobi.commons.MetadataDatabaseConfigurationRetriever.loadConfigurations:88 - The table sbi_config is EMPTY
[http-nio-8080-exec-12] 06 Jul 2021 17:28:53,242 ERROR it.eng.spagobi.commons.utilities.ChannelUtilities.isWebRunning:161 - SPAGOBI.SPAGOBI-MODE.mode IS NULL
[http-nio-8080-exec-12] 06 Jul 2021 17:28:53,244 ERROR it.eng.spagobi.commons.MetadataDatabaseConfigurationRetriever.loadConfigurations:88 - The table sbi_config is EMPTY
[http-nio-8080-exec-12] 06 Jul 2021 17:28:53,245 ERROR it.eng.spagobi.commons.utilities.SpagoBIUtilities.readJndiResource:320 - java.lang.NullPointerException
[http-nio-8080-exec-12] 06 Jul 2021 17:28:53,245 ERROR it.eng.spagobi.services.common.SsoServiceFactory.createProxyService:55 - Error occurred
java.lang.NullPointerException
        at java.lang.Class.forName0(Native Method)
...
```
any help about how to fix this problem is welcome ;O)

**Comment by kerny3d** [comment]
Hi,

the 8.1.0-SNAPSHOT it's in development stage. I suggest you to use the latest stable version 7.4 or wait for the 8.0 in the next weeks.

In the meantime, I thank you for your report and we'll try to investigate your case ASAP.

**Comment by agaldemas-eridanis** [comment]
Hello, Marco, May be we can close this issue !, I'll do with my other github account...

**Comment by agaldemas** [comment]
time to close... will open a new one in case
