### ISSUE TITLE
several errors when starting 8.1, and unable to use REST dataset

### ISSUE THREAD

**Issue by agaldemas** [KnowageLabs/Knowage-Server-Docker#59]
Hello,
I'm trying to update our knowage statefulset  from 8.05 to 8.1, I tried to do an update by keeping the main database, but when the knowage server start, we find some errors about Scheduler:

```
2022-10-27T13:08:28,959+00:00 [501d5a13-38dc-4fab-b4e7-8bd2362c4ad0] ERROR [Catalina-utility-2] [it.eng.spagobi.tools.s
cheduler.init.CleanCacheQuartzInitializer.initCleanForDefaultTenant:101] [] [] []
Error while initializing scheduler
it.eng.spagobi.commons.dao.SpagoBIDAOException: An unexpected error occured while loading job [CleanCacheJob] in group
[CleanCacheJob]
        at it.eng.spagobi.tools.scheduler.dao.quartz.QuarzSchedulerDAOImpl.loadJob(QuarzSchedulerDAOImpl.java:304) ~[kn
owage-dao-8.1.2-SNAPSHOT.jar:8.1.2-SNAPSHOT]
...

2022-10-27T13:08:29,649+00:00 [f12166e3-264a-4bd1-970a-5388051adf95] ERROR [Catalina-utility-2] [it.eng.spagobi.commons.initializers.caching.CachingInitializer.init:59] [] [] []
Cannot initialize cache
it.eng.spagobi.utilities.exceptions.SpagoBIRuntimeException: An error occurred while creating connection
        at it.eng.spagobi.tools.dataset.common.dataproxy.JDBCDataProxy.load(JDBCDataProxy.java:103) ~[knowage-utils-8.1.2-SNAPSHOT.jar:8.1.2-SNAPSHOT]
...
```
No particular issue with the above errors, the knowage works
but when I want to test a simple REST dataset, a error message is displayed in the interface, and we can see the error in knowage.log:

```
2022-10-27T13:13:41,727+00:00 [0813c5b6-7826-4756-8ed2-e9f72b53a191] ERROR [http-nio-8080-exec-2] [it.eng.spagobi.rest.interceptors.RestExceptionMapper.toResponse:60] [75893de3-f31c-431a-a11e-7c85cf3d808b] [] [DEFAULT_TENANT]
Catched service error:
it.eng.spagobi.utilities.exceptions.SpagoBIServiceException: An unexpected error occured while retriving dataset from request
        at it.eng.spagobi.tools.dataset.service.ManageDataSetsForREST.getDataSet(ManageDataSetsForREST.java:1842) ~[knowage-core-8.1.2-SNAPSHOT.jar:8.1.2-SNAPSHOT]
        at it.eng.spagobi.tools.dataset.service.ManageDataSetsForREST.getDataSetResultsAsJSON(ManageDataSetsForREST.java:1732) ~[knowage-core-8.1.2-SNAPSHOT.jar:8.1.2-SNAPSHOT]
        at it.eng.spagobi.tools.dataset.service.ManageDataSetsForREST.datasetTest(ManageDataSetsForREST.java:1711) ~[knowage-core-8.1.2-SNAPSHOT.jar:8.1.2-SNAPSHOT]
        at it.eng.spagobi.tools.dataset.service.ManageDataSetsForREST.previewDataset(ManageDataSetsForREST.java:161) ~[knowage-core-8.1.2-SNAPSHOT.jar:8.1.2-SNAPSHOT]
        at it.eng.spagobi.api.DataSetResource.previewDataSet(DataSetResource.java:846) ~[knowage-core-8.1.2-SNAPSHOT.jar:8.1.2-SNAPSHOT]
...
very long exception trace... going through resteasy, 
...
Caused by: org.json.JSONException: Cannot deserialize instance of `com.fasterxml.jackson.databind.node.ObjectNode` out
of START_ARRAY token
 at [Source: (String)"[]"; line: 1, column: 1]
        at org.json.JSONObject.<init>(JSONObject.java:123) ~[knowage-utils-json-8.1.2-SNAPSHOT.jar:8.1.2-SNAPSHOT]
        at it.eng.spagobi.tools.dataset.service.ManageDataSetsForREST.manageRESTDataSet(ManageDataSetsForREST.java:1482
) ~[knowage-core-8.1.2-SNAPSHOT.jar:8.1.2-SNAPSHOT]
...

```
I've also the same error like in issue #57

I tried with the docker-compose.yaml and I have the same issues...
We absolutely need to upgrade in 8.1, for the many fixes in the release notes, in particular the one for timestamp excel export...
So if you have an idea to save us, I'll be glad.

Thanks in advance

**Comment by agaldemas-eridanis** [comment]
hello, to follow issue from my professional account

**Comment by agaldemas** [comment]
Hello, I manage to have the excel export with timestamps, by upgrading to 8.0.19....

So I close the issue, since this was the only feature missing..

Still the "CleanCacheQuartzInitializer" error is there at start :
[Catalina-utility-4] 29 Oct 2022 21:31:56,619 ERROR it.eng.spagobi.tools.scheduler.init.CleanCacheQuartzInitializer.initCleanForTenant:110 - Error while initializing scheduler 
it.eng.spagobi.commons.dao.SpagoBIDAOException: An unexpected error occured while loading job [CleanCacheJob] in group [CleanCacheJob]
        at it.eng.spagobi.tools.scheduler.dao.quartz.QuarzSchedulerDAOImpl.loadJob(QuarzSchedulerDAOImpl.java:304)

**Comment by agaldemas** [comment]
I'll come back, about CleanCacheQuartzInitializer, since we have noticed that Knowage became very slow after several days of use, and we need to restart it to recover performance !
