### ISSUE TITLE
GC overhead and jarfile validation in docker-compose

### ISSUE THREAD

**Issue by robomotic** [KnowageLabs/Knowage-Server-Docker#9]
Hello guys,
I have run the docker-compose file and I am getting this error:

> INFO: validateJarFile(/home/knowage/apache-tomcat-7.0.57/webapps/knowagekpiengine/WEB-INF/lib/jsp-api-2.1.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/el/Expression.class

When I then connect to the web admin interface, I get an out of memory error:

```
knowage_1    | Jun 08, 2018 4:41:17 PM org.apache.catalina.startup.HostConfig deployDirectories
knowage_1    | SEVERE: Error waiting for multi-thread deployment of directories to complete
knowage_1    | java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: GC overhead limit exceeded
knowage_1    | 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
knowage_1    | 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
knowage_1    | 	at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1148)
knowage_1    | 	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:490)
knowage_1    | 	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1611)
knowage_1    | 	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:330)
knowage_1    | 	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
knowage_1    | 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
knowage_1    | 	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402)
knowage_1    | 	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:347)
knowage_1    | 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:1140)
knowage_1    | 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:816)
knowage_1    | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
knowage_1    | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
knowage_1    | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
knowage_1    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
knowage_1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
knowage_1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
knowage_1    | 	at java.lang.Thread.run(Thread.java:745)
knowage_1    | Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
knowage_1    | 	at java.util.Arrays.copyOfRange(Arrays.java:3664)
knowage_1    | 	at java.lang.String.<init>(String.java:207)
knowage_1    | 	at java.io.DataInputStream.readUTF(DataInputStream.java:661)
knowage_1    | 	at org.apache.tomcat.util.bcel.classfile.FastDataInputStream.readUTF(FastDataInputStream.java:183)
knowage_1    | 	at org.apache.tomcat.util.bcel.classfile.ConstantUtf8.getInstance(ConstantUtf8.java:38)
knowage_1    | 	at org.apache.tomcat.util.bcel.classfile.Constant.readConstant(Constant.java:81)
knowage_1    | 	at org.apache.tomcat.util.bcel.classfile.ConstantPool.<init>(ConstantPool.java:55)
knowage_1    | 	at org.apache.tomcat.util.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:175)
knowage_1    | 	at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:83)
knowage_1    | 	at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2071)
knowage_1    | 	at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:1947)
knowage_1    | 	at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1913)
knowage_1    | 	at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1898)
knowage_1    | 	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1330)
knowage_1    | 	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:889)
knowage_1    | 	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:386)
knowage_1    | 	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
knowage_1    | 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
knowage_1    | 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5380)
knowage_1    | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
knowage_1    | 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
knowage_1    | 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
knowage_1    | 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
knowage_1    | 	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1245)
knowage_1    | 	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1895)
knowage_1    | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
knowage_1    | 	... 4 more

```

**Comment by robomotic** [comment]
Hello, the GC error was due to my Docker memory configuration. The offending class is still an issue but it doesn't seem to affect the overall service.
Cheers.
